import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const templatesDir = resolve(here, "..", "templates");
const outPath = resolve(here, "..", "src", "embedded-templates.ts");

const YAML_SUFFIX = ".yaml";
const files = readdirSync(templatesDir).filter((name) =>
  name.endsWith(YAML_SUFFIX)
);
files.sort();

const entries = files
  .map((file) => {
    const name = file.slice(0, -YAML_SUFFIX.length);
    const content = readFileSync(join(templatesDir, file), "utf-8");
    return `  ${JSON.stringify(name)}: ${JSON.stringify(content)},`;
  })
  .join("\n");

const source = `// Auto-generated by scripts/embed-templates.ts — do not edit by hand.
// Regenerate with \`bun run embed-templates\` (chained from build / build:bin).
//
// Exists so compiled binaries (bun build --compile) can still resolve
// templates when the templates/ directory isn't present on disk alongside
// the binary.

export const EMBEDDED_TEMPLATES: Record<string, string> = {
${entries}
};
`;

writeFileSync(outPath, source);
process.stdout.write(
  `embed-templates: wrote ${outPath} (${files.length} templates)\n`
);
